### ISSUE TITLE
can't edit wiki?

### ISSUE THREAD

**Issue by steaminghacker** [joshwarecom/20x20x2021#1]
permissions?

**Comment by joshwarecom** [comment]
Have you accepted the collaboration invite? Github indicates yours is still pending, screenshot below:

![image](https://user-images.githubusercontent.com/12718039/125002414-db701e00-e022-11eb-9e27-34cdc1699433.png)

**Comment by steaminghacker** [comment]
THanks. email didnt arrive, i found the invite here and accepted it.
